# commit to be tagged for the new release
commit = "HEAD"

project_name = "kube-service-exposer"
github_repo = "siderolabs/kube-service-exposer"
match_deps = "^github.com/(siderolabs/[a-zA-Z0-9-]+)$"

previous = "v0.1.2"

